# Versão do Ubuntu
dist: focal

# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         

# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.8"                                                                                                                                                                                              

addons:
  sonarcloud:
    organization: voltodev
    token: ${SONAR_TOKEN}

# Instalação de Módulos que são necessários para a Aplicação.                                                                                                                                            
install:                                                                                                                                                                                                 
  - pip install flask pytest flask-wtf

# Defini o script de Teste que deve rodar toda vez que o código for alterado.                                                                                                                            
script:                                                                                                                                                                                                  
  - python -m unittest -v test || travis_terminate 1;
  - sonar-scanner || travis_terminate 1;

# Definir o Deploy no Heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: voltodevtest
  on:
      branch: main  